BEGIN;

CREATE TABLE IF NOT EXISTS tutor_review (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tutor_id UUID REFERENCES client (id) ON DELETE CASCADE,
  from_id UUID REFERENCES client (id) ON DELETE CASCADE,
  stars SMALLINT NOT NULL,
  review TEXT,
  UNIQUE (tutor_id, from_id)
);

COMMIT;