BEGIN;

CREATE TABLE IF NOT EXISTS scheduled_event (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  title VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS tutor_session (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tutor_id UUID REFERENCES client (id) ON DELETE RESTRICT,
  updated_by UUID REFERENCES client (id) ON DELETE RESTRICT,
  room_id VARCHAR(40) NOT NULL,
  state VARCHAR(15) NOT NULL,
  event_id INT REFERENCES scheduled_event (id)
);

CREATE TABLE IF NOT EXISTS session_client (
  id SERIAL PRIMARY KEY,
  client_id UUID REFERENCES client (id) ON DELETE CASCADE,
  session_id INT REFERENCES tutor_session (id) ON DELETE CASCADE,
  can_attend BOOLEAN,
  UNIQUE (session_id, client_id)
);

CREATE TABLE IF NOT EXISTS client_event (
  id SERIAL PRIMARY KEY,
  client_id UUID REFERENCES client (id) ON DELETE CASCADE,
  event_id INT REFERENCES scheduled_event (id) ON DELETE CASCADE,
  UNIQUE (event_id, client_id)
);

COMMIT;