BEGIN;

CREATE TABLE IF NOT EXISTS auth (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  token TEXT,
  auth_type VARCHAR(20),
  email VARCHAR(40) UNIQUE,
  password_hash BYTEA,
  UNIQUE (auth_type, token)
);

COMMIT;