BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS client (
  id UUID NOT NULL DEFAULT gen_random_uuid(), 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_name VARCHAR(40),
  last_name VARCHAR(40),
  about TEXT,
  email VARCHAR(40),
  photo VARCHAR(120),
  CONSTRAINT id_tbl PRIMARY KEY ( id )
);

ALTER TABLE IF EXISTS auth 
  ADD COLUMN client_id UUID;

ALTER TABLE IF EXISTS auth 
  DROP CONSTRAINT IF EXISTS fk_client_id;

ALTER TABLE auth 
   ADD CONSTRAINT fk_client_id
   FOREIGN KEY (client_id) 
   REFERENCES client(id);

COMMIT;