BEGIN;

ALTER TABLE IF EXISTS client 
  ADD COLUMN is_tutor BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS client
  ADD COLUMN verified_work_email BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS client
  ADD COLUMN verified_email BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS client
  ADD COLUMN work_email VARCHAR(40);

COMMIT;