version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    secrets:
      - db-password
      - rsa
      - public-rsa
      - fire-base-auth
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 8010
    ports:
      - 8010:8010
    links:
      - database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_URI=postgres://tutorme:__PASSWORD__@database:5432/tutorme?sslmode=disable
      - RSA_FILE=/run/secrets/rsa
      - PUBLIC_RSA_FILE=/run/secrets/public-rsa
      - FIREBASE_AUTH_FILE=/run/secrets/fire-base-auth
    volumes:
      - ./:/app

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    secrets:
      - db-password
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tutorme"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=tutorme
      - POSTGRES_DB=tutorme
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

volumes:
  database_data:
    driver: local
secrets:
  db-password:
    file: db/password.txt
  fire-base-auth:
    file: firebase/tutorproject-292921-firebase-adminsdk-ki5at-7e9eb74043.json
  rsa:
    file: id_rsa
  public-rsa:
    file: id_rsa.pub.pkcs8