version: "3.9"
services:
  javascriptconsumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer.javascript
    depends_on:
      pubsub:
        condition: service_healthy
    links:
      - pubsub
      - backend
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - GOOGLE_CLOUD_PROJECT=tutorproject-292921
      - API_KEY=9ab270da-307a-40a7-be5c-12285f24161e
      - API_HOST=http://backend:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    secrets:
      - db-password
      - rsa
      - public-rsa
      - fire-base-auth
    depends_on:
      database:
        condition: service_healthy
      pubsub:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - database
      - pubsub
    environment:
      - DB_USER=rfrl
      - INSTANCE_CONNECTION_NAME=database
      - DB_NAME=rfrl
      - DB_SSL_MODE=disable
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - RSA_FILE=/run/secrets/rsa
      - PUBLIC_RSA_FILE=/run/secrets/public-rsa
      - FIREBASE_AUTH_FILE=/run/secrets/fire-base-auth
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - GOOGLE_CLOUD_PROJECT=tutorproject-292921
      - BACKEND_TYPE=dev
      - API_KEY=9ab270da-307a-40a7-be5c-12285f24161e
    volumes:
      - ./:/app

  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.pubsub
    expose:
      - 8681
    ports:
      - 8681:8681
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8681"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "none"
    environment:
      - PUBSUB_PROJECT_ID=tutorproject-292921
      - PUBSUB_EMULATOR_HOST=localhost:8681

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    secrets:
      - db-password
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rfrl"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=rfrl
      - POSTGRES_DB=rfrl
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

volumes:
  database_data:
    driver: local
secrets:
  db-password:
    file: db/password.txt
  fire-base-auth:
    file: firebase/tutorproject-292921-firebase-adminsdk-ki5at-7e9eb74043.json
  rsa:
    file: id_rsa
  public-rsa:
    file: id_rsa.pub