FROM node:14-slim

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY consumer/javascript/package*.json ./
COPY consumer/javascript/index.js ./

RUN npm ci --only=production
# If you are building your code for production
# RUN npm ci --only=production

RUN npm install -g nodemon

CMD [ "nodemon", "/index.js"]